namespace EasyPub.Core;

internal static class LegacyTemplates
{
    public static readonly string Container = """
<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
""".Replace("\n", "\r\n") + "\r\n";

    public static List<string> XhtmlHeader(string title) =>
    [
        "<?xml version=\"1.0\" encoding=\"utf-8\" ?>",
        "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">",
        "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"zh-CN\">",
        "<head>",
        "<meta http-equiv=\"Content-Type\" content=\"application/xhtml+xml; charset=utf-8\" />",
        "<meta name=\"generator\" content=\"EasyPub v1.50\" />",
        "<title>", title, "</title>",
        "<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\"/>",
        "</head>", "<body>",
    ];

    private static readonly string StyleCss = """
/*  Generated by EasyPub  */
/*  此css由EasyPub自动生成  */
/*  部分参考老牛中文样式  */



@page { 
      margin-top: 0px;
      margin-bottom: 0px;
}

body { 
      padding: 0;
      margin-left: 3px;
      margin-right: 3px;
      orphans: 0;
      widows: 0;
}

p { 
      font-size: 110%;
      line-height: 120%;
      margin-top: 0.6em;
      margin-bottom: 0;
      margin-left: 0;
      margin-right: 0;
      orphans: 0;
      widows: 0;
}

.a { 
      text-indent: 0em;
}

div.centeredimage {
      text-align:center;
      display:block;
      margin-top: 0.5em;
      margin-bottom: 0.5em;
}

img.attpic {
      border: 1px solid #000000;
      max-width: 100%;
      margin: 0;
}

.booktitle {
      margin-top: 30%;
      margin-bottom: 0;
      border-style: none solid none none;
      border-width: 50px;
      border-color: #4E594D;
      font-size: 3em;
      line-height: 120%;
      text-align: right;
}

.bookauthor {
      margin-top: 0;
      border-style: none solid none none;
      border-width: 50px;
      border-color: #4E594D;
      page-break-after: always;
      font-size: large;
      line-height: 120%;
      text-align: right;
}

.titletoc, .titlel1top, .titlel1std,.titlel2top, .titlel2std,.titlel3top, .titlel3std,.titlel4std {
      margin-top: 0;
      border-style: none double none solid;
      border-width: 0px 5px 0px 20px;
      border-color: #586357;
      background-color: #C1CCC0;
      padding: 45px 5px 5px 5px;
      font-size: x-large;
      line-height: 115%;
      text-align: justify;
}

.titlel1single,.titlel2single,.titlel3single {
      margin-top: 35%;
      border-style: none solid none none;
      border-width: 30px;
      border-color: #4E594D;
      padding: 30px 5px 5px 5px;
      font-size: x-large;
      line-height: 125%;
      text-align: right;
}

.toc {
      margin-left:16%;
      padding:0px;
      line-height:130%;
      text-align: justify;
}

.toc a { text-decoration: none; color: #000000; }

.tocl1 {
      margin-top:0.5em;
      margin-left:-30px;
      border-style: none double double solid;
      border-width: 0px 5px 2px 20px;
      border-color: #6B766A;
      line-height: 135%;
      font-size: 132%;
}

.tocl2 {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none double none solid;
      border-width: 0px 2px 0px 10px;
      border-color: #939E92;
      line-height: 123%;
      font-size: 120%;
}

.tocl3 {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none double none solid;
      border-width: 0px 2px 0px 8px;
      border-color: #939E92;
      line-height: 112%;
      font-size: 109%;
}

.tocl4 {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none double none solid;
      border-width: 0px 2px 0px 6px;
      border-color: #939E92;
      line-height: 115%;
      font-size: 110%;
}

.subtoc {
      margin-left:15%;
      padding:0px;
      text-align: justify;
}

.subtoclist {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none double none solid;
      border-width: 0px 2px 0px 10px;
      border-color: #939E92;
      line-height: 123%;
      font-size: 120%;
}

""".Replace("\n", "\r\n") + "\r\n";

    private static readonly string MobiStyleCss = """
/*  Generated by EasyPub  */
/*  此css由EasyPub自动生成  */
/*  部分参考老牛中文样式  */



body { 
      padding: 0;
      margin-left: 3px;
      margin-right: 3px;
      orphans: 0;
      widows: 0;
}

p { 
      font-size: 110%;
      line-height: 120%;
      margin-top: 0.6em;
      margin-bottom: 0;
      margin-left: 0;
      margin-right: 0;
      orphans: 0;
      widows: 0;
}

.a { 
      text-indent: 0em;
}

div.centeredimage {
      text-align:center;
      display:block;
      margin-top: 0.5em;
      margin-bottom: 0.5em;
}

img.attpic {
      border: 1px solid #000000;
      max-width: 100%;
      margin: 0;
}

.booktitle {
      margin-top: 30%;
      margin-bottom: 0;
      border-style: none solid none none;
      border-width: 50px;
      border-color: #4E594D;
      font-size: 3em;
      line-height: 120%;
      text-align: right;
}

.bookauthor {
      margin-top: 0;
      border-style: none solid none none;
      border-width: 50px;
      border-color: #4E594D;
      page-break-after: always;
      font-size: large;
      line-height: 120%;
      text-align: right;
}

@media not amzn-mobi {
.titletoc, .titlel1top, .titlel1std,.titlel2top, .titlel2std,.titlel3top, .titlel3std,.titlel4std {
      margin-top: 0;
      margin-bottom: 1.2em;
      border-style: none none dotted none;
      border-width: 0px 0px 1px 0px;
      border-color: #C1CCC0;
      padding: 10px 0 10px 0;
      font-size: x-large;
      line-height: 125%;
      text-align: center;
      text-shadow: 1px 1px 1px #333;
}

.titlel1single,.titlel2single,.titlel3single {
      margin-top: 35%;
      border-style: none solid none none;
      border-width: 30px;
      border-color: #4E594D;
      padding: 30px 5px 5px 5px;
      font-size: x-large;
      line-height: 110%;
      text-align: right;
}
}

@media amzn-mobi {
.titletoc, .titlel1top, .titlel1std,.titlel2top, .titlel2std,.titlel3top, .titlel3std,.titlel4std {
      margin-top: 0;
      padding-top: 20px;
      font-size: x-large;
      line-height: 125%;
      text-align: center;
}

.titlel1single,.titlel2single,.titlel3single {
      margin-top: 35%;
      line-height: 110%;
      font-size: x-large;
      text-align: center;
}
}

.toc {
      margin-left:12%;
      padding:0px;
      line-height:130%;
      text-align: justify;
}

.toc a { text-decoration: none; color: #000000; }

.tocl1 {
      margin-top:0.5em;
      margin-left:-30px;
      border-style: none double double solid;
      border-width: 0px 5px 2px 20px;
      border-color: #6B766A;
      line-height: 135%;
      font-size: 132%;
}

.tocl2 {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none none none none;
      line-height: 123%;
      font-size: 120%;
}


.tocl3 {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none double none solid;
      border-width: 0px 2px 0px 8px;
      border-color: #939E92;
      line-height: 112%;
      font-size: 109%;
}

.tocl4 {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none double none solid;
      border-width: 0px 2px 0px 6px;
      border-color: #939E92;
      line-height: 115%;
      font-size: 110%;
}

.subtoc {
      margin-left:15%;
      padding:0px;
      text-align: justify;
}

.subtoclist {
      margin-top: 0.5em;
      margin-left:-20px;
      border-style: none double none solid;
      border-width: 0px 2px 0px 10px;
      border-color: #939E92;
      line-height: 123%;
      font-size: 120%;
}

""".Replace("\n", "\r\n") + "\r\n";

    public static string CreateStyleCss(ConversionOptions options)
    {
        return ApplyOptions(StyleCss, options, includePageMargins: true);
    }

    public static string CreateMobiStyleCss(ConversionOptions options)
    {
        return ApplyOptions(MobiStyleCss, options, includePageMargins: false);
    }

    private static string ApplyOptions(string template, ConversionOptions options, bool includePageMargins)
    {
        var css = template
            .Replace("margin-top: 0px;", $"margin-top: {options.PageMarginTopPx}px;", StringComparison.Ordinal)
            .Replace("margin-bottom: 0px;", $"margin-bottom: {options.PageMarginBottomPx}px;", StringComparison.Ordinal)
            .Replace("margin-left: 3px;", $"margin-left: {options.PageMarginLeftPx}px;", StringComparison.Ordinal)
            .Replace("margin-right: 3px;", $"margin-right: {options.PageMarginRightPx}px;", StringComparison.Ordinal)
            .Replace("font-size: 110%;", $"font-size: {options.FontSizePercent}%;", StringComparison.Ordinal)
            .Replace("line-height: 120%;", $"line-height: {options.LineHeightPercent}%;", StringComparison.Ordinal)
            .Replace("margin-top: 0.6em;", $"margin-top: {options.ParagraphSpacingEm:0.###}em;", StringComparison.Ordinal)
            .Replace("text-indent: 0em;", $"text-indent: {options.ParagraphIndentEm:0.###}em;", StringComparison.Ordinal);

        if (options.TextAlignment != TextAlignment.Default)
            css = css.Replace("text-align: justify;", $"text-align: {Alignment(options.TextAlignment)};", StringComparison.Ordinal);

        if (!includePageMargins && (options.PageMarginTopPx != 0 || options.PageMarginBottomPx != 0))
            css += $"\r\n@page {{ margin-top: {options.PageMarginTopPx}px; margin-bottom: {options.PageMarginBottomPx}px; }}\r\n";

        if (options.Illustrations.Count > 0)
            css += "\r\n/* Body illustrations */\r\n.illustration { text-align: center; margin: 1em 0; }\r\n.body-illustration { max-width: 100%; height: auto; }\r\n";

        if (options.Font.Enabled && !string.IsNullOrWhiteSpace(options.Font.FontPath))
        {
            var fallback = Path.GetFileNameWithoutExtension(options.Font.FontPath);
            var family = (string.IsNullOrWhiteSpace(options.Font.FamilyName) ? fallback : options.Font.FamilyName.Trim())
                .Replace("\\", string.Empty, StringComparison.Ordinal)
                .Replace("'", "\\'", StringComparison.Ordinal);
            css = $"@font-face {{ font-family: '{family}'; src: url('fonts/book.ttf'); }}\r\nbody, p, h1, h2, h3, div, span, a {{ font-family: '{family}'; }}\r\n" + css;
        }

        if (string.IsNullOrWhiteSpace(options.AdditionalCss)) return css;
        return css + "\r\n/*  User CSS  */\r\n" + options.AdditionalCss.Trim() + "\r\n";
    }

    private static string Alignment(TextAlignment alignment) => alignment switch
    {
        TextAlignment.Left => "left",
        TextAlignment.Center => "center",
        TextAlignment.Right => "right",
        _ => "justify",
    };
}
