using System.Security.Cryptography;
using System.Text;

namespace EasyPub.Core;

/// <summary>One first-before-edit copy per source path; never a chapter-tree file.</summary>
public sealed class SourceBackupStore(string directory)
{
    public string DirectoryPath { get; } = Path.GetFullPath(directory);

    public static SourceBackupStore CreateDefault() => new(
        Environment.GetEnvironmentVariable("EASYPUB_SOURCE_BACKUPS_PATH") ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "EasyPub Modern", "SourceBackups"));

    public string BackupPath(string sourcePath)
    {
        var full = Path.GetFullPath(sourcePath);
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(full.ToUpperInvariant())));
        return Path.Combine(DirectoryPath, hash, Path.GetFileName(full) + ".bak");
    }

    public string EnsureBackup(string sourcePath)
    {
        var full = Path.GetFullPath(sourcePath);
        var backup = BackupPath(full);
        Directory.CreateDirectory(Path.GetDirectoryName(backup)!);
        if (File.Exists(backup)) return backup;
        var temporary = backup + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.Copy(full, temporary, overwrite: false);
            try { File.Move(temporary, backup, overwrite: false); }
            catch (IOException) when (File.Exists(backup)) { /* Another editor already saved the original. */ }
            return backup;
        }
        finally { if (File.Exists(temporary)) File.Delete(temporary); }
    }

    public IReadOnlyList<string> FindBackups(string sourcePath)
    {
        var full = Path.GetFullPath(sourcePath);
        var files = new List<string>();
        if (File.Exists(BackupPath(full))) files.Add(BackupPath(full));
        var snapshots = Path.Combine(Path.GetDirectoryName(BackupPath(full))!, "Snapshots");
        if (Directory.Exists(snapshots)) files.AddRange(Directory.EnumerateFiles(snapshots, "*.bak"));
        var parent = Path.GetDirectoryName(full)!;
        if (Directory.Exists(parent))
        {
            // Only list the exact legacy naming scheme generated by this application.
            var prefix = Path.GetFileName(full) + ".";
            foreach (var path in Directory.EnumerateFiles(parent, "*.bak"))
            {
                var name = Path.GetFileName(path);
                if (name.Length == prefix.Length + 32 + 4 && name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)
                    && Guid.TryParseExact(name[prefix.Length..^4], "N", out _)) files.Add(path);
            }
        }
        return files.OrderByDescending(File.GetLastWriteTimeUtc).ToArray();
    }

    public string EnsureSnapshot(ChapterTreeDocument document)
    {
        var bytes = File.ReadAllBytes(document.SourcePath);
        var hash = Convert.ToHexString(SHA256.HashData(bytes));
        if (!string.Equals(hash, document.SourceSha256, StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException("原始 TXT 已在外部修改，请关闭章节工作台并重新打开后再修复。");
        EnsureBackup(document.SourcePath);
        var directory = Path.Combine(Path.GetDirectoryName(BackupPath(document.SourcePath))!, "Snapshots");
        Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, hash + ".bak");
        try
        {
            using var output = new FileStream(path, FileMode.CreateNew, FileAccess.Write);
            output.Write(bytes);
        }
        catch (IOException) when (File.Exists(path))
        {
            if (!SHA256.HashData(File.ReadAllBytes(path)).SequenceEqual(SHA256.HashData(bytes))) throw;
        }
        return path;
    }
}
